package com.nitish.qa.enums;

public enum ConfigProperties {
    URL,
    BROWSER,
    OVERRIDE_REPORTS,
    PASSED_STEPS_SCREENSHOTS,
    FAILED_STEPS_SCREENSHOTS,
    SKIPPED_STEPS_SCREENSHOTS,
    RETRY_FAILED_TESTS,
    TEST_SELECTION_STRATEGY,
    EXECUTION_MODE,
    TEST_CATEGORY,
    GRID_URL
}
